import path from 'node:path';
import fs from 'node:fs';
import os from 'node:os';
import { execFileSync } from 'node:child_process';

const HELP = `
omm wiki2pdf [options]

Convert Markdown files (like the wiki generated by 'omm wiki') into a single styled PDF document.
Requires Google Chrome, Microsoft Edge, or Chromium installed.

Usage:
  omm wiki2pdf                      Convert Markdown files in current directory to ./documentation.pdf
  omm wiki2pdf --src <dir>          Specify source directory containing .md files
  omm wiki2pdf --out <file.pdf>     Specify output path for the generated PDF
  omm wiki2pdf --title <title>      Set project title (default: auto-detected)
  omm wiki2pdf --menu <config>      Ordering menu: 'auto' (default), 'none', or path to JSON
  omm wiki2pdf --color <hex>        Primary accent color (default: "#6366f1")
`;

// Helper to escape HTML characters
function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

// Inline Markdown Parser
function parseInline(text: string): string {
  let escaped = escapeHtml(text);

  // Bold **text**
  escaped = escaped.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');

  // Italic *text*
  escaped = escaped.replace(/\*(.*?)\*/g, '<em>$1</em>');

  // Inline code `text`
  escaped = escaped.replace(/`([^`]+)`/g, '<code>$1</code>');

  // Standard links [text](url) — change .md targets to hash anchors for unified document
  escaped = escaped.replace(/\[([^\]]+)\]\(([^)]+)\)/g, (match, linkText, url) => {
    let target = url;
    // Block dangerous protocols
    if (/^(javascript|data|vbscript):/i.test(target)) target = '#';
    if (target.endsWith('.md')) {
      const base = target.slice(0, -3).replace(/\//g, '_');
      return `<a href="#article-${base}">${linkText}</a>`;
    }
    return `<a href="${target}">${linkText}</a>`;
  });

  // Wikilinks [[target]] or [[target|custom text]] — map to anchor links in combined manual
  escaped = escaped.replace(/\[\[([^\]]+)\]\]/g, (match, content) => {
    let target = content.trim();
    let linkText = target;

    if (target.includes('|')) {
      const parts = target.split('|');
      target = parts[0].trim();
      linkText = parts[1].trim();
    }

    let href = target.replace(/\//g, '_');
    if (href.endsWith('.md')) {
      href = href.slice(0, -3);
    }
    
    return `<a href="#article-${href}">${linkText}</a>`;
  });

  // Images ![alt](url)
  escaped = escaped.replace(/!\[([^\]]*)\]\(([^)]+)\)/g, '<img src="$2" alt="$1">');

  return escaped;
}

/**
 * Sanitize Mermaid diagram source to fix common syntax issues.
 * - Replaces @ in labels (conflicts with Mermaid directives)
 * - Renames reserved keywords used as node IDs
 * - Replaces <> angle brackets in labels (interpreted as HTML)
 */
function sanitizeMermaid(src: string): string {
  let out = src;

  // Reserved keywords that cannot be used as node IDs
  const RESERVED = /^(graph|flowchart|subgraph|end|class|click|style|linkStyle|interpolate|init|beta|accTitle|accDescr|\|)$/i;

  // Replace @ in label text with → (Mermaid treats @ as directive prefix)
  out = out.replace(/\["(.*?)"\]/g, (match, label) => {
    const fixed = label.replace(/@/g, '→ ');
    return `["${fixed}"]`;
  });

  // Replace <> angle brackets in label text with [] (Mermaid treats <> as HTML)
  out = out.replace(/\["(.*?)"\]/g, (match, label) => {
    const fixed = label.replace(/</g, '[').replace(/>/g, ']');
    return `["${fixed}"]`;
  });

  // Rename reserved keyword node IDs by appending -node
  out = out.replace(/^(\s*)(\S+)(\[)/gm, (match, indent, nodeId, bracket) => {
    if (RESERVED.test(nodeId)) {
      return `${indent}${nodeId}-node${bracket}`;
    }
    return match;
  });

  return out;
}

// Block Markdown Parser
function parseMarkdown(md: string): string {
  let html = '';
  const lines = md.split(/\r?\n/);
  let inCode = false;
  let codeLang = '';
  let codeLines: string[] = [];
  let inList = false;
  let listType: 'ul' | 'ol' | null = null;
  let inBlockquote = false;
  let inTable = false;
  let tableHeaders: string[] = [];
  let tableRows: string[][] = [];

  function closeList() {
    if (inList) {
      html += listType === 'ul' ? '</ul>\n' : '</ol>\n';
      inList = false;
      listType = null;
    }
  }

  function closeBlockquote() {
    if (inBlockquote) {
      html += '</blockquote>\n';
      inBlockquote = false;
    }
  }

  function closeTable() {
    if (inTable) {
      html += '<table>\n<thead>\n<tr>\n';
      for (const h of tableHeaders) {
        html += `<th>${parseInline(h)}</th>\n`;
      }
      html += '</tr>\n</thead>\n<tbody>\n';
      for (const r of tableRows) {
        html += '<tr>\n';
        for (const cell of r) {
          html += `<td>${parseInline(cell)}</td>\n`;
        }
        html += '</tr>\n';
      }
      html += '</tbody>\n</table>\n';
      inTable = false;
      tableHeaders = [];
      tableRows = [];
    }
  }

  function closeBlocks() {
    closeList();
    closeBlockquote();
    closeTable();
  }

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    // Code block check
    if (line.trim().startsWith('```')) {
      if (inCode) {
        inCode = false;
        const codeText = codeLines.join('\n');
        if (codeLang === 'mermaid') {
          html += `<div class="mermaid-container">\n<div class="mermaid">\n${escapeHtml(sanitizeMermaid(codeText))}\n</div>\n</div>\n`;
        } else {
          html += `<pre><code class="language-${escapeHtml(codeLang)}">${escapeHtml(codeText)}</code></pre>\n`;
        }
        codeLines = [];
        codeLang = '';
      } else {
        closeBlocks();
        inCode = true;
        codeLang = line.trim().slice(3).trim();
      }
      continue;
    }

    if (inCode) {
      codeLines.push(line);
      continue;
    }

    // Blank line
    if (line.trim() === '') {
      closeBlocks();
      continue;
    }

    // Blockquote
    const bqMatch = line.match(/^\s*>\s?(.*)$/);
    if (bqMatch) {
      if (!inBlockquote) {
        closeBlocks();
        html += '<blockquote>\n';
        inBlockquote = true;
      }
      html += `${parseInline(bqMatch[1])}<br>\n`;
      continue;
    } else {
      closeBlockquote();
    }

    // Table rows
    const isTableRow = line.trim().startsWith('|') && line.trim().endsWith('|');
    if (isTableRow) {
      closeList();
      const cells = line.split('|').map(c => c.trim()).slice(1, -1);
      if (!inTable) {
        // Look ahead to check for separator row
        const nextLine = lines[i + 1];
        if (nextLine && nextLine.trim().startsWith('|') && nextLine.includes('---')) {
          inTable = true;
          tableHeaders = cells;
          i++; // skip separator
        } else {
          closeTable();
          html += `<p>${parseInline(line)}</p>\n`;
        }
      } else {
        tableRows.push(cells);
      }
      continue;
    } else {
      closeTable();
    }

    // Headings
    const hMatch = line.match(/^(#{1,6})\s+(.*)$/);
    if (hMatch) {
      closeBlocks();
      const level = hMatch[1].length;
      html += `<h${level}>${parseInline(hMatch[2])}</h${level}>\n`;
      continue;
    }

    // Unordered List
    const ulMatch = line.match(/^\s*[-*+]\s+(.*)$/);
    if (ulMatch) {
      if (!inList || listType !== 'ul') {
        closeBlocks();
        html += '<ul>\n';
        inList = true;
        listType = 'ul';
      }
      html += `<li>${parseInline(ulMatch[1])}</li>\n`;
      continue;
    }

    // Ordered List
    const olMatch = line.match(/^\s*(\d+)\.\s+(.*)$/);
    if (olMatch) {
      if (!inList || listType !== 'ol') {
        closeBlocks();
        html += '<ol>\n';
        inList = true;
        listType = 'ol';
      }
      html += `<li>${parseInline(olMatch[2])}</li>\n`;
      continue;
    }

    // Horizontal rule
    if (line.match(/^\s*([-*_])\1\1+\s*$/)) {
      closeBlocks();
      html += '<hr>\n';
      continue;
    }

    // Paragraph
    closeBlocks();
    html += `<p>${parseInline(line)}</p>\n`;
  }

  closeBlocks();
  return html;
}

// Extract first H1 or fall back to title-cased filename
function getMarkdownInfo(filePath: string, baseName: string): { title: string } {
  let title = '';
  try {
    const content = fs.readFileSync(filePath, 'utf-8');
    const lines = content.split(/\r?\n/).slice(0, 15);
    for (const line of lines) {
      const match = line.match(/^#\s+(.+)$/);
      if (match) {
        title = match[1].trim();
        break;
      }
    }
  } catch {
    // Ignore
  }
  if (!title) {
    let name = baseName.replace(/^\d+[\s._-]*/, '').replace(/[\s_-]+/g, ' ');
    title = name.replace(/\b\w/g, c => c.toUpperCase());
  }
  return { title };
}

// Auto-discover Chrome/Chromium executable
function findChromeExecutable(): string | null {
  const macPaths = [
    '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
    '/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary',
    '/Applications/Chromium.app/Contents/MacOS/Chromium',
  ];
  const winPaths = [
    'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
    'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
    'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',
    'C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe',
  ];
  const linuxPaths = [
    '/usr/bin/google-chrome',
    '/usr/bin/chromium-browser',
    '/usr/bin/chromium',
    '/usr/bin/chrome',
  ];

  if (process.platform === 'darwin') {
    for (const p of macPaths) {
      if (fs.existsSync(p)) return p;
    }
    try {
      const pathOnMac = execFileSync('which', ['Google Chrome'], { stdio: 'pipe' }).toString().trim();
      if (pathOnMac) return pathOnMac;
    } catch {}
  } else if (process.platform === 'win32') {
    for (const p of winPaths) {
      if (fs.existsSync(p)) return p;
    }
    // Fallback: check PATH using 'where' (Windows equivalent of 'which')
    const winNames = ['chrome.exe', 'msedge.exe', 'chromium.exe'];
    for (const name of winNames) {
      try {
        const output = execFileSync('where', [name], { stdio: 'pipe' }).toString().trim();
        if (output) {
          // 'where' may return multiple lines; take the first match
          const first = output.split(/\r?\n/)[0].trim();
          if (first && fs.existsSync(first)) return first;
        }
      } catch {}
    }
  } else {
    for (const p of linuxPaths) {
      if (fs.existsSync(p)) return p;
    }
    const pathFinder = ['google-chrome', 'chromium-browser', 'chromium', 'chrome'];
    for (const name of pathFinder) {
      try {
        const p = execFileSync('which', [name], { stdio: 'pipe' }).toString().trim();
        if (p) return p;
      } catch {}
    }
  }
  return null;
}

// HTML template for PDF generation (strictly white background, no interactive elements)
const PDF_HTML_TEMPLATE = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>$title$</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Fira+Code:wght@400;500&display=swap');

        @page {
            size: portrait;
            margin: 20mm 15mm;
        }

        @page landscape-page {
            size: landscape;
            margin: 15mm;
        }

        .landscape-section {
            page: landscape-page;
        }

        body {
            font-family: 'Inter', sans-serif;
            background-color: #ffffff;
            color: #0f172a;
            margin: 0;
            padding: 40px;
            line-height: 1.7;
        }

        /* Cover Page Styling */
        .cover-page {
            height: 95vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            text-align: center;
            box-sizing: border-box;
            padding: 40px;
            page-break-after: always;
            break-after: page;
        }

        .cover-title {
            font-size: 42px;
            font-weight: 800;
            margin-bottom: 16px;
            color: #0f172a;
            border-bottom: none !important;
            padding-bottom: 0 !important;
        }

        .cover-subtitle {
            font-size: 18px;
            color: #475569;
            margin-bottom: 60px;
            font-weight: 500;
        }

        .cover-date {
            font-size: 14px;
            color: #64748b;
        }

        /* Page break separator */
        .wiki-section {
            page-break-before: always;
            break-before: page;
        }

        /* Avoid breaking components across pages */
        table, pre, .mermaid-container, blockquote, img {
            page-break-inside: avoid !important;
            break-inside: avoid !important;
        }

        h1, h2, h3, h4, h5, h6 {
            page-break-after: avoid !important;
            break-after: avoid !important;
            color: #0f172a;
            font-weight: 600;
        }

        h1 {
            font-size: 28px;
            border-bottom: 2px solid #cbd5e1;
            padding-bottom: 10px;
            margin-top: 30px;
        }

        h2 {
            font-size: 22px;
            border-bottom: 1px solid #e2e8f0;
            padding-bottom: 8px;
            margin-top: 24px;
        }

        h3 {
            font-size: 18px;
            margin-top: 20px;
        }

        a {
            color: PRIMARYCOLOR;
            text-decoration: none;
            border-bottom: 1px dotted PRIMARYCOLOR;
        }

        /* Code blocks styling */
        code {
            background-color: #f1f5f9;
            padding: 2px 5px;
            border-radius: 4px;
            font-size: 13px;
            font-family: 'Fira Code', monospace;
            color: #0f766e;
        }

        pre {
            background-color: #f8fafc;
            padding: 16px;
            border-radius: 8px;
            overflow-x: auto;
            font-size: 13px;
            font-family: 'Fira Code', monospace;
            border: 1px solid #cbd5e1;
            margin: 20px 0;
        }

        pre code {
            background-color: transparent;
            padding: 0;
            border-radius: 0;
            color: #0f172a;
        }

        img {
            max-width: 100%;
            height: auto;
            border-radius: 8px;
            border: 1px solid #cbd5e1;
        }

        /* Table layout */
        table {
            border-collapse: separate;
            border-spacing: 0;
            width: 100%;
            margin: 20px 0;
            border-radius: 8px;
            overflow: hidden;
            border: 1px solid #cbd5e1;
        }

        th, td {
            padding: 10px 12px;
            text-align: left;
        }

        th {
            background-color: #f1f5f9;
            font-weight: 600;
            border-bottom: 1px solid #cbd5e1;
        }

        td {
            border-bottom: 1px solid #cbd5e1;
            color: #334155;
        }

        tr:last-child td {
            border-bottom: none;
        }

        blockquote {
            border-left: 4px solid PRIMARYCOLOR;
            padding: 4px 16px;
            margin: 20px 0;
            background-color: #f8fafc;
            color: #475569;
            font-style: italic;
        }

        .mermaid-container {
            border: 1px solid #cbd5e1;
            border-radius: 8px;
            padding: 24px;
            background: #ffffff;
            margin: 20px 0;
            display: flex;
            justify-content: center;
        }

        .mermaid-container svg {
            max-width: 100% !important;
            height: auto !important;
            display: block;
        }

        /* Hide screen-only styling */
        @media print {
            body {
                padding: 0;
            }
            .mermaid-container {
                border: none !important;
                padding: 0 !important;
                margin: 10px 0 !important;
            }
        }
    </style>
</head>
<body>
    BODY
    <script src="https://cdn.jsdelivr.net/npm/mermaid@10.7.0/dist/mermaid.min.js"></script>
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            mermaid.initialize({
                startOnLoad: true,
                theme: 'default',
                themeVariables: {
                    fontSize: '16px',
                    fontFamily: "'Inter', sans-serif"
                },
                flowchart: { useMaxWidth: true, htmlLabels: true },
                sequence: { useMaxWidth: true, htmlLabels: true },
                er: { useMaxWidth: true, htmlLabels: true }
            });
        });
    </script>
</body>
</html>
`;

export async function commandWiki2Pdf(args: string[]): Promise<void> {
  let srcDir = process.cwd();
  let outPath = path.join(process.cwd(), 'documentation.pdf');
  
  // Resolve default project title from package.json or directory name
  let defaultTitle = 'Documentation';
  try {
    const pkgPath = path.join(process.cwd(), 'package.json');
    if (fs.existsSync(pkgPath)) {
      const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
      if (pkg.name) {
        defaultTitle = pkg.name
          .replace(/[-_]+/g, ' ')
          .replace(/\b\w/g, (c: string) => c.toUpperCase());
      }
    } else {
      defaultTitle = path.basename(process.cwd())
        .replace(/[-_]+/g, ' ')
        .replace(/\b\w/g, (c: string) => c.toUpperCase());
    }
  } catch {
    // ignore
  }

  let title = defaultTitle;
  let menuConfig = 'auto';
  let primaryColor = '#6366f1';
  let help = false;

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg === '--src' && args[i + 1]) srcDir = args[++i];
    else if (arg === '--out' && args[i + 1]) outPath = args[++i];
    else if (arg === '--title' && args[i + 1]) title = args[++i];
    else if (arg === '--menu' && args[i + 1]) menuConfig = args[++i];
    else if (arg === '--color' && args[i + 1]) primaryColor = args[++i];
    else if (arg === '--help' || arg === '-h') help = true;
  }

  if (args.length === 0 || help) {
    process.stdout.write(HELP.trim() + '\n');
    return;
  }

  if (primaryColor && !/^#[0-9a-fA-F]{3,8}$/.test(primaryColor)) {
    process.stderr.write('error: --color must be a valid hex color (e.g. #6366f1)\n');
    process.exit(1);
  }

  if (!fs.existsSync(srcDir) || !fs.statSync(srcDir).isDirectory()) {
    process.stderr.write(`error: Source directory "${srcDir}" does not exist or is not a directory.\n`);
    process.exit(1);
  }

  // 1. Locate Chrome binary
  const chromePath = findChromeExecutable();
  if (!chromePath) {
    process.stderr.write('error: Google Chrome, Microsoft Edge, or Chromium was not found on your system.\n');
    process.stderr.write('wiki2pdf requires a Chromium-based browser to render Mermaid graphs and compile to PDF headlessly.\n');
    process.stderr.write('Please install Google Chrome or Microsoft Edge and try again.\n');
    process.exit(1);
  }

  // 2. Fetch list of Markdown files in the directory
  const mdFiles = fs.readdirSync(srcDir)
    .filter(f => f.endsWith('.md'))
    .sort();

  if (mdFiles.length === 0) {
    process.stderr.write(`error: No Markdown (.md) files found in "${srcDir}"\n`);
    process.exit(1);
  }

  // Ensure output directory for PDF exists
  const resolvedOutPath = path.resolve(outPath);
  const outDir = path.dirname(resolvedOutPath);
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }

  // 3. Resolve the menu items mapping list to order sections correctly
  const menuItemsList: { title: string; file: string }[] = [];

  if (menuConfig === 'auto' || !menuConfig) {
    const indexExists = fs.existsSync(path.join(srcDir, 'index.md'));
    const readmeExists = fs.existsSync(path.join(srcDir, 'README.md'));
    
    if (indexExists) {
      menuItemsList.push({ title: 'Home', file: 'index.md' });
    } else if (readmeExists) {
      menuItemsList.push({ title: 'README', file: 'README.md' });
    }

    const otherFiles = mdFiles.filter(f => f !== 'index.md' && f !== 'README.md');
    for (const file of otherFiles) {
      const baseName = path.basename(file, '.md');
      const info = getMarkdownInfo(path.join(srcDir, file), baseName);
      menuItemsList.push({ title: info.title, file });
    }
  } else if (menuConfig !== 'none') {
    try {
      const jsonPath = path.resolve(menuConfig);
      if (fs.existsSync(jsonPath)) {
        const content = fs.readFileSync(jsonPath, 'utf-8');
        const customMenu = JSON.parse(content);
        if (Array.isArray(customMenu)) {
          for (const item of customMenu) {
            // Find MD file in srcDir matching item.url filename
            const matchName = item.url.replace(/\.html$/, '.md');
            if (fs.existsSync(path.join(srcDir, matchName))) {
              menuItemsList.push({ title: item.title, file: matchName });
            }
          }
        }
      }
    } catch (err: any) {
      process.stdout.write(`Warning: Failed to load menu config json: ${err.message}. Falling back to 'auto'.\n`);
      menuConfig = 'auto';
    }
  } else {
    // none - just add index.md or README.md if they exist
    const indexExists = fs.existsSync(path.join(srcDir, 'index.md'));
    const readmeExists = fs.existsSync(path.join(srcDir, 'README.md'));
    if (indexExists) {
      menuItemsList.push({ title: 'Home', file: 'index.md' });
    } else if (readmeExists) {
      menuItemsList.push({ title: 'README', file: 'README.md' });
    }
  }

  // 4. Generate the Cover Page HTML
  const currentDate = new Date().toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  let combinedBody = `
    <div class="cover-page">
        <h1 class="cover-title">${escapeHtml(title)}</h1>
        <p class="cover-subtitle">Architecture Reference Manual &amp; Documentation</p>
        <p class="cover-date">Generated on ${currentDate}</p>
    </div>
  `;

  // 5. Concatenate and Render all articles with page breaks
  for (const item of menuItemsList) {
    const fullPath = path.join(srcDir, item.file);
    const baseName = path.basename(item.file, '.md');
    
    let rawContent = '';
    try {
      rawContent = fs.readFileSync(fullPath, 'utf-8');
    } catch {
      continue;
    }

    // Strip metadata sections if generated by wiki (e.g. --- \n name: index \n ---)
    let markdownToParse = rawContent;
    if (rawContent.startsWith('---')) {
      const endMeta = rawContent.indexOf('---', 3);
      if (endMeta !== -1) {
        markdownToParse = rawContent.slice(endMeta + 3).trim();
      }
    }

    // Parse Markdown to HTML
    const renderedBody = parseMarkdown(markdownToParse);

    // Apply landscape page styling for sections that contain diagrams
    const hasMermaid = renderedBody.includes('class="mermaid"');
    const sectionClass = hasMermaid ? 'wiki-section landscape-section' : 'wiki-section';

    // Append section with an ID matching the link hash target
    combinedBody += `
      <section class="${sectionClass}" id="article-${baseName.replace(/\//g, '_')}">
        ${renderedBody}
      </section>
    `;
  }

  // 6. Output to a temporary HTML file in os.tmpdir()
  const tempHtmlFile = path.join(os.tmpdir(), `__pdf_temp_combined_${Date.now()}.html`);
  const finalHTML = PDF_HTML_TEMPLATE
    .replace(/\$title\$/g, `${title} - Manual`)
    .replace(/PRIMARYCOLOR/g, primaryColor)
    .replace(/BODY/g, combinedBody);

  fs.writeFileSync(tempHtmlFile, finalHTML, 'utf-8');

  // 7. Execute Headless Chrome to print the HTML file to a single PDF
  process.stdout.write(`Compiling PDF using Google Chrome...\n`);
  try {
    execFileSync(chromePath, [
      '--headless',
      '--disable-gpu',
      `--print-to-pdf=${resolvedOutPath}`,
      '--virtual-time-budget=10000',
      '--run-all-compositor-stages-before-draw',
      tempHtmlFile
    ], { stdio: 'pipe' });
    
    process.stdout.write(`[SUCCESS] PDF generated successfully!\n`);
    process.stdout.write(`[SUCCESS] PDF file is at ${resolvedOutPath}\n`);
  } catch (err: any) {
    process.stderr.write(`error: Headless Chrome failed to write PDF: ${err.message}\n`);
  } finally {
    // 8. Cleanup temporary HTML file
    try {
      if (fs.existsSync(tempHtmlFile)) {
        fs.unlinkSync(tempHtmlFile);
      }
    } catch {
      // ignore
    }
  }
}
