import path from 'node:path';
import fs from 'node:fs';
import { execFile } from 'node:child_process';

const HELP = `
omm wiki2html [options]

Convert Markdown files (like the wiki generated by 'omm wiki') into a styled HTML documentation site.

Usage:
  omm wiki2html                      Convert Markdown files in current directory to ./html
  omm wiki2html --src <dir>          Specify source directory containing .md files
  omm wiki2html --out <dir>          Specify output directory for generated HTML
  omm wiki2html --title <title>      Set project title (default: auto-detected)
  omm wiki2html --menu <config>      Sidebar menu: 'auto' (default), 'none', or path to JSON
  omm wiki2html --color <hex>        Primary theme color (default: "#6366f1")
  omm wiki2html --no-open            Do not open index.html in browser upon completion
  omm wiki2html --create-menu        Create sample menu.json based on files in source dir
  omm wiki2html --menu-path <path>   Output path for sample menu JSON (default: "./menu.json")
`;

// Helper to escape HTML characters
function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

// Inline Markdown Parser
function parseInline(text: string): string {
  let escaped = escapeHtml(text);

  // Bold **text**
  escaped = escaped.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');

  // Italic *text*
  escaped = escaped.replace(/\*(.*?)\*/g, '<em>$1</em>');

  // Inline code `text`
  escaped = escaped.replace(/`([^`]+)`/g, '<code>$1</code>');

  // Standard links [text](url) — if target ends with .md, convert to .html
  escaped = escaped.replace(/\[([^\]]+)\]\(([^)]+)\)/g, (match, linkText, url) => {
    let target = url;
    // Block dangerous protocols
    if (/^(javascript|data|vbscript):/i.test(target)) target = '#';
    if (target.endsWith('.md')) {
      target = target.slice(0, -3) + '.html';
    }
    return `<a href="${target}">${linkText}</a>`;
  });

  // Wikilinks [[target]] or [[target|custom text]]
  escaped = escaped.replace(/\[\[([^\]]+)\]\]/g, (match, content) => {
    let target = content.trim();
    let linkText = target;

    if (target.includes('|')) {
      const parts = target.split('|');
      target = parts[0].trim();
      linkText = parts[1].trim();
    }

    // Replace slashes with underscores as wiki generator does for filenames
    let href = target.replace(/\//g, '_');
    if (href.endsWith('.md')) {
      href = href.slice(0, -3);
    }
    if (!href.endsWith('.html') && href !== 'index') {
      href += '.html';
    } else if (href === 'index') {
      href = 'index.html';
    }

    return `<a href="${href}">${linkText}</a>`;
  });

  // Images ![alt](url)
  escaped = escaped.replace(/!\[([^\]]*)\]\(([^)]+)\)/g, '<img src="$2" alt="$1">');

  return escaped;
}

/**
 * Sanitize Mermaid diagram source to fix common syntax issues.
 * - Replaces @ in labels (conflicts with Mermaid directives)
 * - Renames reserved keywords used as node IDs
 * - Replaces <> angle brackets in labels (interpreted as HTML)
 */
function sanitizeMermaid(src: string): string {
  let out = src;

  // Reserved keywords that cannot be used as node IDs
  const RESERVED = /^(graph|flowchart|subgraph|end|class|click|style|linkStyle|interpolate|init|beta|accTitle|accDescr|\|)$/i;

  // Replace @ in node IDs with _at_ (Mermaid treats @ as directive prefix)
  // Match @word at start of line (after optional whitespace) followed by [ or -->
  out = out.replace(/^(\s*)@([\w-]+)/gm, (match, indent, name) => {
    return `${indent}_at_${name}`;
  });
  // Also replace @ in edge targets: --> @node or --> @node[
  out = out.replace(/-->(?:\|[^|]*\|)?\s*@([\w-]+)/g, (match, name) => {
    return match.replace(`@${name}`, `_at_${name}`);
  });

  // Replace @ in label text with → (Mermaid treats @ as directive prefix)
  out = out.replace(/\["(.*?)"\]/g, (match, label) => {
    const fixed = label.replace(/@/g, '→ ');
    return `["${fixed}"]`;
  });

  // Replace <> angle brackets in label text with [] (Mermaid treats <> as HTML)
  out = out.replace(/\["(.*?)"\]/g, (match, label) => {
    const fixed = label.replace(/</g, '[').replace(/>/g, ']');
    return `["${fixed}"]`;
  });

  // Rename reserved keyword node IDs by appending -node
  out = out.replace(/^(\s*)(\S+)(\[)/gm, (match, indent, nodeId, bracket) => {
    if (RESERVED.test(nodeId)) {
      return `${indent}${nodeId}-node${bracket}`;
    }
    return match;
  });

  // Fix edge references to renamed reserved node IDs
  out = out.replace(/-->.*/gm, (edgeLine) => {
    return edgeLine.replace(/\|(\s*\S+\s*)\|/g, (labelMatch, label) => labelMatch);
  });

  return out;
}

// Block Markdown Parser
function parseMarkdown(md: string): string {
  let html = '';
  const lines = md.split(/\r?\n/);
  let inCode = false;
  let codeLang = '';
  let codeLines: string[] = [];
  let inList = false;
  let listType: 'ul' | 'ol' | null = null;
  let inBlockquote = false;
  let inTable = false;
  let tableHeaders: string[] = [];
  let tableRows: string[][] = [];

  function closeList() {
    if (inList) {
      html += listType === 'ul' ? '</ul>\n' : '</ol>\n';
      inList = false;
      listType = null;
    }
  }

  function closeBlockquote() {
    if (inBlockquote) {
      html += '</blockquote>\n';
      inBlockquote = false;
    }
  }

  function closeTable() {
    if (inTable) {
      html += '<table>\n<thead>\n<tr>\n';
      for (const h of tableHeaders) {
        html += `<th>${parseInline(h)}</th>\n`;
      }
      html += '</tr>\n</thead>\n<tbody>\n';
      for (const r of tableRows) {
        html += '<tr>\n';
        for (const cell of r) {
          html += `<td>${parseInline(cell)}</td>\n`;
        }
        html += '</tr>\n';
      }
      html += '</tbody>\n</table>\n';
      inTable = false;
      tableHeaders = [];
      tableRows = [];
    }
  }

  function closeBlocks() {
    closeList();
    closeBlockquote();
    closeTable();
  }

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    // Code block check
    if (line.trim().startsWith('```')) {
      if (inCode) {
        inCode = false;
        const codeText = codeLines.join('\n');
        if (codeLang === 'mermaid') {
          html += `<div class="mermaid-container">\n<div class="mermaid">\n${escapeHtml(sanitizeMermaid(codeText))}\n</div>\n</div>\n`;
        } else {
          html += `<pre><code class="language-${escapeHtml(codeLang)}">${escapeHtml(codeText)}</code></pre>\n`;
        }
        codeLines = [];
        codeLang = '';
      } else {
        closeBlocks();
        inCode = true;
        codeLang = line.trim().slice(3).trim();
      }
      continue;
    }

    if (inCode) {
      codeLines.push(line);
      continue;
    }

    // Blank line
    if (line.trim() === '') {
      closeBlocks();
      continue;
    }

    // Blockquote
    const bqMatch = line.match(/^\s*>\s?(.*)$/);
    if (bqMatch) {
      if (!inBlockquote) {
        closeBlocks();
        html += '<blockquote>\n';
        inBlockquote = true;
      }
      html += `${parseInline(bqMatch[1])}<br>\n`;
      continue;
    } else {
      closeBlockquote();
    }

    // Table rows
    const isTableRow = line.trim().startsWith('|') && line.trim().endsWith('|');
    if (isTableRow) {
      closeList();
      const cells = line.split('|').map(c => c.trim()).slice(1, -1);
      if (!inTable) {
        // Look ahead to check for separator row
        const nextLine = lines[i + 1];
        if (nextLine && nextLine.trim().startsWith('|') && nextLine.includes('---')) {
          inTable = true;
          tableHeaders = cells;
          i++; // skip separator
        } else {
          closeTable();
          html += `<p>${parseInline(line)}</p>\n`;
        }
      } else {
        tableRows.push(cells);
      }
      continue;
    } else {
      closeTable();
    }

    // Headings
    const hMatch = line.match(/^(#{1,6})\s+(.*)$/);
    if (hMatch) {
      closeBlocks();
      const level = hMatch[1].length;
      html += `<h${level}>${parseInline(hMatch[2])}</h${level}>\n`;
      continue;
    }

    // Unordered List
    const ulMatch = line.match(/^\s*[-*+]\s+(.*)$/);
    if (ulMatch) {
      if (!inList || listType !== 'ul') {
        closeBlocks();
        html += '<ul>\n';
        inList = true;
        listType = 'ul';
      }
      html += `<li>${parseInline(ulMatch[1])}</li>\n`;
      continue;
    }

    // Ordered List
    const olMatch = line.match(/^\s*(\d+)\.\s+(.*)$/);
    if (olMatch) {
      if (!inList || listType !== 'ol') {
        closeBlocks();
        html += '<ol>\n';
        inList = true;
        listType = 'ol';
      }
      html += `<li>${parseInline(olMatch[2])}</li>\n`;
      continue;
    }

    // Horizontal rule
    if (line.match(/^\s*([-*_])\1\1+\s*$/)) {
      closeBlocks();
      html += '<hr>\n';
      continue;
    }

    // Paragraph
    closeBlocks();
    html += `<p>${parseInline(line)}</p>\n`;
  }

  closeBlocks();
  return html;
}

// Extract first H1 or fall back to title-cased filename
function getMarkdownInfo(filePath: string, baseName: string): { title: string } {
  let title = '';
  try {
    const content = fs.readFileSync(filePath, 'utf-8');
    const lines = content.split(/\r?\n/).slice(0, 15);
    for (const line of lines) {
      const match = line.match(/^#\s+(.+)$/);
      if (match) {
        title = match[1].trim();
        break;
      }
    }
  } catch {
    // Ignore
  }
  if (!title) {
    let name = baseName.replace(/^\d+[\s._-]*/, '').replace(/[\s_-]+/g, ' ');
    title = name.replace(/\b\w/g, c => c.toUpperCase());
  }
  return { title };
}

// Build table of contents for a page
function generateTOC(html: string): { tocHTML: string; bodyHTML: string } {
  let bodyHTML = html;
  const tocItems: string[] = [];
  let headerIndex = 0;

  bodyHTML = bodyHTML.replace(/<(h[23]) id="([^"]+)"/gi, (match, tag, existingId) => {
    return match;
  });

  // Inject IDs and build list
  bodyHTML = bodyHTML.replace(/<(h[23])>(.*?)<\/\1>/gi, (match, tag, titleText) => {
    const cleanText = titleText.replace(/<[^>]*>/g, '').trim();
    const id = 'header-' + cleanText.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') + '-' + headerIndex++;
    tocItems.push(`<li class="toc-item ${tag}"><a href="#${id}">${titleText}</a></li>`);
    return `<${tag} id="${id}">${titleText}</${tag}>`;
  });

  if (tocItems.length === 0) {
    return { tocHTML: '', bodyHTML };
  }

  const tocHTML = `
    <div class="toc-container">
      <div class="toc-title">On this page</div>
      <ul class="toc-list">
        ${tocItems.join('\n')}
      </ul>
    </div>
  `;
  return { tocHTML, bodyHTML };
}

// Build the sidebar navigation list
function buildNavigationMenu(
  sourceDir: string,
  menuConfig: string,
  activeBaseName: string,
  menuItemsList: { title: string; url: string }[]
): string {
  const getActiveCls = (href: string) => {
    return href === `${activeBaseName}.html` ? ' class="active"' : '';
  };

  const htmlItems: string[] = [];

  for (const item of menuItemsList) {
    htmlItems.push(`<li><a href="${item.url}"${getActiveCls(item.url.slice(0, -5))}>${escapeHtml(item.title)}</a></li>`);
  }

  return htmlItems.join('\n');
}

// Create a menu.json file
function createMenuJson(sourceDir: string, outputPath: string): void {
  const menuItems: { title: string; url: string }[] = [];

  const indexExists = fs.existsSync(path.join(sourceDir, 'index.md'));
  if (indexExists) {
    menuItems.push({ title: 'Home', url: 'index.html' });
  }

  const readmeExists = fs.existsSync(path.join(sourceDir, 'README.md'));
  if (readmeExists && !indexExists) {
    menuItems.push({ title: 'README', url: 'README.html' });
  }

  const files = fs.readdirSync(sourceDir)
    .filter(f => f.endsWith('.md') && f !== 'index.md' && f !== 'README.md')
    .sort();

  for (const file of files) {
    const fullPath = path.join(sourceDir, file);
    const baseName = path.basename(file, '.md');
    const info = getMarkdownInfo(fullPath, baseName);
    menuItems.push({ title: info.title, url: `${baseName}.html` });
  }

  fs.writeFileSync(outputPath, JSON.stringify(menuItems, null, 2), 'utf-8');
  process.stdout.write(`Sample menu JSON file created successfully at ${outputPath}\n`);
}

// Main HTML Template
const HTML_TEMPLATE = `<!DOCTYPE html>
<html lang="en" data-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>$title$</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Fira+Code:wght@400;500&display=swap');

        :root {
            --primary-color: PRIMARYCOLOR;
            --bg-main: #0b0f19;
            --bg-sidebar: #111827;
            --bg-content: #0b0f19;
            --text-main: #f3f4f6;
            --text-muted: #9ca3af;
            --border-color: #1f2937;
            --bg-code: #1f2937;
        }

        [data-theme="light"] {
            --bg-main: #f8fafc;
            --bg-sidebar: #f1f5f9;
            --bg-content: #f8fafc;
            --text-main: #0f172a;
            --text-muted: #475569;
            --border-color: #cbd5e1;
            --bg-code: #e2e8f0;
        }

        body {
            font-family: 'Inter', sans-serif;
            background-color: var(--bg-main);
            color: var(--text-main);
            margin: 0;
            padding: 0;
            line-height: 1.7;
            transition: background-color 0.3s, color 0.3s;
            overflow-x: hidden; /* prevent tiny body scrollbar */
        }

        /* Custom Scrollbars */
        ::-webkit-scrollbar {
            width: 8px;
            height: 8px;
        }
        ::-webkit-scrollbar-track {
            background: var(--bg-sidebar);
        }
        ::-webkit-scrollbar-thumb {
            background: var(--border-color);
            border-radius: 4px;
        }
        ::-webkit-scrollbar-thumb:hover {
            background: var(--primary-color);
        }

        .container {
            display: flex;
            min-height: 100vh;
        }

        .sidebar {
            width: 300px;
            background: var(--bg-sidebar);
            border-right: 1px solid var(--border-color);
            position: fixed;
            height: 100vh;
            overflow-y: auto;
            overflow-x: hidden; /* prevent horizontal scrollbar */
            left: 0;
            top: 0;
            box-sizing: border-box;
            padding: 24px;
            display: flex;
            flex-direction: column;
            transition: background-color 0.3s, border-color 0.3s;
        }

        .sidebar-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 24px;
        }

        .sidebar-title-link {
            text-decoration: none;
            border-bottom: none;
            display: inline-block;
        }

        .sidebar-title-link:hover {
            border-bottom: none;
        }

        .sidebar h2 {
            font-size: 20px;
            font-weight: 700;
            margin: 0;
            background: linear-gradient(135deg, #fff 0%, var(--primary-color) 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }

        [data-theme="light"] .sidebar h2 {
            background: linear-gradient(135deg, #0f172a 0%, var(--primary-color) 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }

        .theme-toggle-btn {
            background: transparent;
            border: 1px solid var(--border-color);
            border-radius: 8px;
            width: 36px;
            height: 36px;
            display: flex;
            align-items: center;
            justify-content: center;
            cursor: pointer;
            color: var(--text-main);
            transition: all 0.2s;
            font-size: 16px;
        }

        .theme-toggle-btn:hover {
            background: rgba(255, 255, 255, 0.05);
            border-color: var(--primary-color);
        }

        [data-theme="light"] .theme-toggle-btn:hover {
            background: rgba(0, 0, 0, 0.05);
        }

        .search-box {
            position: relative;
            margin-bottom: 20px;
        }

        #search-input {
            width: 100%;
            padding: 10px 36px 10px 16px; /* right padding to clear search x icon */
            background: rgba(255, 255, 255, 0.03);
            border: 1px solid var(--border-color);
            border-radius: 8px;
            color: var(--text-main);
            font-size: 14px;
            box-sizing: border-box;
            outline: none;
            transition: all 0.2s;
        }

        [data-theme="light"] #search-input {
            background: rgba(0, 0, 0, 0.02);
        }

        #search-input:focus {
            border-color: var(--primary-color);
            background: rgba(255, 255, 255, 0.06);
            box-shadow: 0 0 0 3px rgba(99, 102, 241, 0.15);
        }

        [data-theme="light"] #search-input:focus {
            background: rgba(0, 0, 0, 0.04);
        }

        .search-clear-btn {
            position: absolute;
            right: 12px;
            top: 50%;
            transform: translateY(-50%);
            background: transparent;
            border: none;
            color: var(--text-muted);
            font-size: 18px;
            cursor: pointer;
            display: none;
            padding: 0;
            line-height: 1;
            z-index: 5;
        }

        .search-clear-btn:hover {
            color: var(--text-main);
        }

        .search-results {
            position: absolute;
            top: 100%;
            left: 0;
            right: 0;
            background: var(--bg-sidebar);
            border: 1px solid var(--border-color);
            border-radius: 8px;
            margin-top: 8px;
            max-height: 250px;
            overflow-y: auto;
            overflow-x: hidden;
            z-index: 100;
            display: none;
            box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.3);
        }

        .search-results.active {
            display: block;
        }

        .search-item {
            padding: 10px 14px;
            border-bottom: 1px solid var(--border-color);
            transition: background-color 0.2s;
        }

        .search-item:last-child {
            border-bottom: none;
        }

        .search-item:hover {
            background: rgba(255, 255, 255, 0.04);
        }

        [data-theme="light"] .search-item:hover {
            background: rgba(0, 0, 0, 0.03);
        }

        .search-item a {
            display: block;
            text-decoration: none;
            color: var(--text-main);
            border-bottom: none;
        }

        .search-item-title {
            font-weight: 600;
            font-size: 14px;
        }

        .search-item-snippet {
            font-size: 12px;
            color: var(--text-muted);
            margin-top: 4px;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
        }

        .sidebar ul {
            padding-left: 0;
            list-style: none;
            margin: 0;
            overflow-y: auto;
            overflow-x: hidden;
            flex-grow: 1;
        }

        .sidebar li {
            margin-bottom: 6px;
        }

        .sidebar a {
            display: block;
            padding: 10px 14px;
            text-decoration: none;
            border-radius: 8px;
            color: var(--text-muted);
            font-weight: 500;
            font-size: 14px;
            transition: all 0.2s cubic-bezier(0.4, 0, 0.2, 1);
        }

        .sidebar a:hover {
            background-color: rgba(255, 255, 255, 0.03);
            color: var(--text-main);
            padding-left: 18px;
        }

        [data-theme="light"] .sidebar a:hover {
            background-color: rgba(0, 0, 0, 0.03);
        }

        .sidebar a.active {
            background-color: var(--primary-color);
            color: #fff;
            font-weight: 600;
            transform: none;
        }

        .content {
            margin-left: 300px;
            padding: 48px 64px;
            max-width: 900px;
            box-sizing: border-box;
        }

        code {
            background-color: var(--bg-code);
            padding: 3px 6px;
            border-radius: 6px;
            font-size: 14px;
            font-family: 'Fira Code', monospace;
            color: #38bdf8;
            border: 1px solid var(--border-color);
        }

        [data-theme="light"] code {
            color: #0369a1;
        }

        pre {
            background-color: #030712;
            padding: 20px;
            border-radius: 12px;
            overflow-x: auto;
            font-size: 14px;
            font-family: 'Fira Code', monospace;
            border: 1px solid var(--border-color);
            margin: 24px 0;
        }

        pre code {
            background-color: transparent;
            padding: 0;
            border-radius: 0;
            color: var(--text-main);
            border: none;
        }

        .code-block-wrapper {
            position: relative;
        }

        .copy-code-btn {
            position: absolute;
            top: 10px;
            right: 10px;
            background: rgba(15, 23, 42, 0.8);
            border: 1px solid var(--border-color);
            border-radius: 6px;
            color: var(--text-muted);
            padding: 4px 8px;
            font-size: 12px;
            cursor: pointer;
            opacity: 0;
            transition: all 0.2s;
        }

        .code-block-wrapper:hover .copy-code-btn {
            opacity: 1;
        }

        .copy-code-btn:hover {
            color: #fff;
            border-color: var(--primary-color);
        }

        img {
            max-width: 100%;
            height: auto;
            border-radius: 8px;
            border: 1px solid var(--border-color);
        }

        table {
            border-collapse: separate;
            border-spacing: 0;
            width: 100%;
            margin: 24px 0;
            border-radius: 12px;
            overflow: hidden;
            border: 1px solid var(--border-color);
        }

        th, td {
            padding: 12px 16px;
            text-align: left;
        }

        th {
            background-color: rgba(255, 255, 255, 0.02);
            font-weight: 600;
            border-bottom: 1px solid var(--border-color);
        }

        [data-theme="light"] th {
            background-color: rgba(0, 0, 0, 0.02);
        }

        td {
            border-bottom: 1px solid var(--border-color);
            color: var(--text-main);
            opacity: 0.9;
        }

        tr:last-child td {
            border-bottom: none;
        }

        tr:hover td {
            background-color: rgba(255, 255, 255, 0.01);
        }

        h1, h2, h3, h4, h5, h6 {
            color: #fff;
            font-weight: 600;
            margin-top: 36px;
            margin-bottom: 16px;
        }

        [data-theme="light"] h1, [data-theme="light"] h2, [data-theme="light"] h3, [data-theme="light"] h4, [data-theme="light"] h5, [data-theme="light"] h6 {
            color: #0f172a;
        }

        h1 {
            font-size: 32px;
            border-bottom: 1px solid var(--border-color);
            padding-bottom: 12px;
            margin-top: 0;
        }

        h2 {
            font-size: 24px;
            border-bottom: 1px solid var(--border-color);
            padding-bottom: 8px;
        }

        h3 {
            font-size: 20px;
        }

        a {
            color: var(--primary-color);
            text-decoration: none;
            font-weight: 500;
            border-bottom: 1px dotted var(--primary-color);
            transition: border-bottom-color 0.2s;
        }

        a:hover {
            border-bottom-style: solid;
        }

        blockquote {
            border-left: 4px solid var(--primary-color);
            padding: 8px 16px;
            margin: 24px 0;
            background-color: rgba(99, 102, 241, 0.04);
            border-radius: 0 8px 8px 0;
            color: var(--text-main);
            opacity: 0.95;
        }

        .toc-container {
            background: rgba(255, 255, 255, 0.01);
            border: 1px solid var(--border-color);
            border-radius: 12px;
            padding: 16px 20px;
            margin-bottom: 32px;
        }

        [data-theme="light"] .toc-container {
            background: rgba(0, 0, 0, 0.01);
        }

        .toc-title {
            font-size: 12px;
            font-weight: 700;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            color: var(--text-muted);
            margin-bottom: 12px;
        }

        .toc-list {
            list-style: none;
            padding-left: 0;
            margin: 0;
        }

        .toc-item {
            margin-bottom: 8px;
        }

        .toc-item.h2 {
            font-size: 14px;
        }

        .toc-item.h3 {
            font-size: 14px;
            padding-left: 16px;
        }

        .toc-item a {
            color: var(--text-muted);
            border-bottom: none;
            transition: color 0.2s;
        }

        .toc-item a:hover {
            color: var(--primary-color);
        }

        .pagination {
            display: flex;
            justify-content: space-between;
            margin-top: 48px;
            padding-top: 24px;
            border-top: 1px solid var(--border-color);
            gap: 16px;
        }

        .pagination-link {
            display: flex;
            flex-direction: column;
            padding: 16px 24px;
            border: 1px solid var(--border-color);
            border-radius: 12px;
            text-decoration: none;
            flex: 1;
            transition: all 0.2s;
            max-width: 50%;
            border-bottom: 1px solid var(--border-color);
        }

        .pagination-link:hover {
            border-color: var(--primary-color);
            background: rgba(255, 255, 255, 0.01);
            transform: translateY(-2px);
        }

        [data-theme="light"] .pagination-link:hover {
            background: rgba(0, 0, 0, 0.01);
        }

        .pagination-label {
            font-size: 11px;
            color: var(--text-muted);
            text-transform: uppercase;
            margin-bottom: 4px;
        }

        .pagination-title {
            font-size: 15px;
            font-weight: 600;
            color: #fff;
        }

        [data-theme="light"] .pagination-title {
            color: #0f172a;
        }

        .pagination-link.prev {
            align-items: flex-start;
        }

        .pagination-link.next {
            align-items: flex-end;
            margin-left: auto;
        }

        .mermaid-container {
            position: relative;
            cursor: zoom-in;
            border: 1px solid var(--border-color);
            border-radius: 12px;
            padding: 24px;
            background: #030712;
            margin: 24px 0;
            transition: all 0.2s;
            overflow-x: auto;
        }

        [data-theme="light"] .mermaid-container {
            background: #fff;
        }

        .mermaid-container:hover {
            border-color: var(--primary-color);
            box-shadow: 0 0 15px rgba(99, 102, 241, 0.1);
        }

        .mermaid-container::after {
            content: '🔍 Click to expand';
            position: absolute;
            bottom: 10px;
            right: 10px;
            font-size: 11px;
            color: var(--text-muted);
            background: rgba(17, 24, 39, 0.8);
            padding: 4px 8px;
            border-radius: 4px;
            border: 1px solid var(--border-color);
            pointer-events: none;
            opacity: 0;
            transition: opacity 0.2s;
        }

        .mermaid-container:hover::after {
            opacity: 1;
        }

        /* Mermaid Modal */
        .mermaid-modal {
            display: none;
            position: fixed;
            z-index: 1000;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(3, 7, 18, 0.95);
            align-items: center;
            justify-content: center;
        }

        .mermaid-modal.active {
            display: flex;
        }

        .mermaid-modal-content {
            position: relative;
            width: 90vw;
            height: 90vh;
            max-width: 90vw;
            max-height: 90vh;
            overflow: hidden; /* custom zooming/panning, no native scrollbars */
            background: #1f2937;
            border-radius: 12px;
            border: 1px solid var(--border-color);
            box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.5);
        }

        [data-theme="light"] .mermaid-modal-content {
            background: #f8fafc;
        }

        .mermaid-modal-close {
            position: absolute;
            top: 24px;
            right: 32px;
            color: #fff;
            font-size: 40px;
            font-weight: bold;
            cursor: pointer;
            transition: color 0.2s;
            z-index: 1010; /* make sure it is above the svg wrapper */
        }

        [data-theme="light"] .mermaid-modal-close {
            color: #0f172a;
        }

        .mermaid-modal-close:hover {
            color: var(--primary-color);
        }

        .mermaid-modal-svg-wrapper {
            width: 100%;
            height: 100%;
            display: flex;
            align-items: center;
            justify-content: center;
            cursor: grab;
            transform-origin: center center;
            user-select: none;
        }

        .mermaid-modal-svg-wrapper:active {
            cursor: grabbing;
        }

        .mermaid-modal-svg-wrapper svg {
            max-width: 100%;
            max-height: 100%;
            width: auto;
            height: auto;
            display: block;
        }

        @media (max-width: 900px) {
            .container {
                flex-direction: column;
            }
            .sidebar {
                position: static;
                width: 100%;
                height: auto;
                border-right: none;
                border-bottom: 1px solid var(--border-color);
            }
            .content {
                margin-left: 0;
                width: 100%;
                padding: 24px;
            }
        }
    </style>
</head>
<body>
    <script>
        (function() {
            const savedTheme = localStorage.getItem("wiki-theme") || "dark";
            document.documentElement.setAttribute("data-theme", savedTheme);
        })();
    </script>
    <div class="container">
        <div class="sidebar">
            <div class="sidebar-header">
                <a href="HOME_LINK_URL" class="sidebar-title-link">
                    <h2>$ProjectTitle$</h2>
                </a>
                <button id="theme-toggle" class="theme-toggle-btn" aria-label="Toggle theme">🌙</button>
            </div>
            <div class="search-box">
                <input type="text" id="search-input" placeholder="Search..." autocomplete="off">
                <button id="search-clear-btn" class="search-clear-btn" aria-label="Clear search">&times;</button>
                <div id="search-results" class="search-results"></div>
            </div>
            <ul>
                NAVIGATION
            </ul>
        </div>
        <div class="content">
            TOC
            BODY
            PAGINATION
        </div>
    </div>

    <!-- Mermaid Modal -->
    <div id="mermaid-modal" class="mermaid-modal">
        <span class="mermaid-modal-close">&times;</span>
        <div class="mermaid-modal-content">
            <div class="mermaid-modal-svg-wrapper" id="mermaid-modal-svg-wrapper"></div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/mermaid@10.7.0/dist/mermaid.min.js"></script>
    <script src="search-index.js"></script>
    <script>
        // Init Mermaid
        document.addEventListener("DOMContentLoaded", function() {
            mermaid.initialize({
                startOnLoad: true,
                theme: 'dark',
                flowchart: { useMaxWidth: true, htmlLabels: true },
                sequence: { useMaxWidth: true, htmlLabels: true },
                er: { useMaxWidth: true, htmlLabels: true }
            });
        });

        // Theme Toggle Script
        document.addEventListener("DOMContentLoaded", function() {
            const toggleBtn = document.getElementById("theme-toggle");
            if (toggleBtn) {
                const getTheme = () => document.documentElement.getAttribute("data-theme") || "dark";
                const setTheme = (theme) => {
                    document.documentElement.setAttribute("data-theme", theme);
                    localStorage.setItem("wiki-theme", theme);
                    toggleBtn.textContent = theme === "dark" ? "🌙" : "☀️";
                };

                toggleBtn.textContent = getTheme() === "dark" ? "🌙" : "☀️";
                toggleBtn.addEventListener("click", function() {
                    setTheme(getTheme() === "dark" ? "light" : "dark");
                });
            }
        });

        // Copy Code Button Script
        document.addEventListener("DOMContentLoaded", function() {
            document.querySelectorAll("pre").forEach(preBlock => {
                const wrapper = document.createElement("div");
                wrapper.className = "code-block-wrapper";
                preBlock.parentNode.insertBefore(wrapper, preBlock);
                wrapper.appendChild(preBlock);

                const copyBtn = document.createElement("button");
                copyBtn.className = "copy-code-btn";
                copyBtn.textContent = "Copy";
                wrapper.appendChild(copyBtn);

                copyBtn.addEventListener("click", function() {
                    const codeText = preBlock.querySelector("code") ? preBlock.querySelector("code").textContent : preBlock.textContent;
                    navigator.clipboard.writeText(codeText).then(() => {
                        copyBtn.textContent = "Copied!";
                        setTimeout(() => { copyBtn.textContent = "Copy"; }, 2000);
                    }).catch(() => {
                        copyBtn.textContent = "Error";
                    });
                });
            });
        });

        // Search Script
        document.addEventListener("DOMContentLoaded", function() {
            const searchInput = document.getElementById("search-input");
            const searchResults = document.getElementById("search-results");
            const clearBtn = document.getElementById("search-clear-btn");

            if (searchInput && searchResults && typeof WIKI_SEARCH_INDEX !== "undefined") {
                const checkClearBtn = () => {
                    if (clearBtn) {
                        clearBtn.style.display = searchInput.value ? "block" : "none";
                    }
                };

                searchInput.addEventListener("input", function() {
                    const query = searchInput.value.toLowerCase().trim();
                    checkClearBtn();

                    if (!query) {
                        searchResults.classList.remove("active");
                        searchResults.innerHTML = "";
                        return;
                    }

                    const filtered = WIKI_SEARCH_INDEX.filter(item =>
                        item.title.toLowerCase().includes(query) ||
                        item.content.toLowerCase().includes(query)
                    ).slice(0, 10);

                    if (filtered.length === 0) {
                        searchResults.innerHTML = '<div class="search-item"><span class="search-item-title" style="color: var(--text-muted);">No results found</span></div>';
                    } else {
                        searchResults.innerHTML = filtered.map(item => {
                            const index = item.content.toLowerCase().indexOf(query);
                            let snippet = "";
                            if (index !== -1) {
                                const start = Math.max(0, index - 30);
                                const end = Math.min(item.content.length, index + query.length + 50);
                                snippet = (start > 0 ? "..." : "") + item.content.substring(start, end).trim() + (end < item.content.length ? "..." : "");
                            } else {
                                snippet = item.content.substring(0, 80) + "...";
                            }
                            snippet = snippet.replace(/<[^>]*>/g, "");
                            // Escape HTML in snippet to prevent XSS
                            snippet = snippet.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
                            return \`
                                <div class="search-item">
                                    <a href="\${item.url}">
                                        <div class="search-item-title">\${item.title}</div>
                                        <div class="search-item-snippet">\${snippet}</div>
                                    </a>
                                </div>
                            \`;
                        }).join("");
                    }
                    searchResults.classList.add("active");
                });

                if (clearBtn) {
                    clearBtn.addEventListener("click", function() {
                        searchInput.value = "";
                        clearBtn.style.display = "none";
                        searchResults.classList.remove("active");
                        searchResults.innerHTML = "";
                        searchInput.focus();
                    });
                }

                document.addEventListener("click", function(e) {
                    if (!searchInput.contains(e.target) && !searchResults.contains(e.target) && (!clearBtn || !clearBtn.contains(e.target))) {
                        searchResults.classList.remove("active");
                    }
                });
            }
        });

        // Mermaid zoom/pan modal
        document.addEventListener("DOMContentLoaded", function() {
            const modal = document.getElementById("mermaid-modal");
            const svgWrapper = document.getElementById("mermaid-modal-svg-wrapper");
            const modalClose = document.querySelector(".mermaid-modal-close");

            if (modal && svgWrapper && modalClose) {
                let scale = 1;
                let panX = 0;
                let panY = 0;
                let isDragging = false;
                let startX, startY;

                function updateTransform() {
                    svgWrapper.style.transform = \`translate(\${panX}px, \${panY}px) scale(\${scale})\`;
                }

                document.querySelectorAll(".mermaid-container").forEach(container => {
                    container.addEventListener("click", function() {
                        const svgElement = container.querySelector(".mermaid svg");
                        if (svgElement) {
                            svgWrapper.innerHTML = svgElement.outerHTML;
                        } else {
                            svgWrapper.innerHTML = container.querySelector(".mermaid").innerHTML;
                        }
                        
                        // Reset zoom and pan
                        scale = 1;
                        panX = 0;
                        panY = 0;
                        updateTransform();
                        
                        modal.classList.add("active");
                    });
                });

                modalClose.addEventListener("click", function() {
                    modal.classList.remove("active");
                });

                modal.addEventListener("click", function(e) {
                    if (e.target === modal) {
                        modal.classList.remove("active");
                    }
                });

                // Close on Esc key
                document.addEventListener("keydown", function(e) {
                    if (e.key === "Escape" && modal.classList.contains("active")) {
                        modal.classList.remove("active");
                    }
                });

                // Zoom with scroll wheel
                svgWrapper.addEventListener("wheel", function(e) {
                    e.preventDefault();
                    const zoomStep = 0.1;
                    if (e.deltaY < 0) {
                        scale = Math.min(scale + zoomStep, 4);
                    } else {
                        scale = Math.max(scale - zoomStep, 0.4);
                    }
                    updateTransform();
                });

                // Pan via mouse dragging
                svgWrapper.addEventListener("mousedown", function(e) {
                    isDragging = true;
                    startX = e.clientX - panX;
                    startY = e.clientY - panY;
                });

                document.addEventListener("mouseup", function() {
                    isDragging = false;
                });

                svgWrapper.addEventListener("mousemove", function(e) {
                    if (!isDragging) return;
                    e.preventDefault();
                    panX = e.clientX - startX;
                    panY = e.clientY - startY;
                    updateTransform();
                });
            }
        });
    </script>
</body>
</html>
`;

export async function commandWiki2Html(args: string[]): Promise<void> {
  let srcDir = process.cwd();
  let outDir = path.join(process.cwd(), 'html');
  
  // Resolve default project title from package.json or directory name
  let defaultTitle = 'Documentation';
  try {
    const pkgPath = path.join(process.cwd(), 'package.json');
    if (fs.existsSync(pkgPath)) {
      const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
      if (pkg.name) {
        defaultTitle = pkg.name
          .replace(/[-_]+/g, ' ')
          .replace(/\b\w/g, (c: string) => c.toUpperCase());
      }
    } else {
      defaultTitle = path.basename(process.cwd())
        .replace(/[-_]+/g, ' ')
        .replace(/\b\w/g, (c: string) => c.toUpperCase());
    }
  } catch {
    // fallback
  }

  let title = defaultTitle;
  let menuConfig = 'auto';
  let primaryColor = '#6366f1';
  let openBrowser = true;
  let createMenu = false;
  let menuJsonPath = path.join(process.cwd(), 'menu.json');
  let help = false;

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg === '--src' && args[i + 1]) srcDir = args[++i];
    else if (arg === '--out' && args[i + 1]) outDir = args[++i];
    else if (arg === '--title' && args[i + 1]) title = args[++i];
    else if (arg === '--menu' && args[i + 1]) menuConfig = args[++i];
    else if (arg === '--color' && args[i + 1]) primaryColor = args[++i];
    else if (arg === '--no-open') openBrowser = false;
    else if (arg === '--create-menu') createMenu = true;
    else if (arg === '--menu-path' && args[i + 1]) menuJsonPath = args[++i];
    else if (arg === '--help' || arg === '-h') help = true;
    else if (!arg.startsWith('-')) srcDir = arg; // positional: source directory
  }

  if (args.length === 0 || help) {
    process.stdout.write(HELP.trim() + '\n');
    return;
  }

  if (primaryColor && !/^#[0-9a-fA-F]{3,8}$/.test(primaryColor)) {
    process.stderr.write('error: --color must be a valid hex color (e.g. #6366f1)\n');
    process.exit(1);
  }

  if (!fs.existsSync(srcDir) || !fs.statSync(srcDir).isDirectory()) {
    process.stderr.write(`error: Source directory "${srcDir}" does not exist or is not a directory.\n`);
    process.exit(1);
  }

  if (createMenu) {
    createMenuJson(srcDir, menuJsonPath);
    return;
  }

  const mdFiles = fs.readdirSync(srcDir)
    .filter(f => f.endsWith('.md'))
    .sort();

  if (mdFiles.length === 0) {
    process.stderr.write(`error: No Markdown (.md) files found in "${srcDir}"\n`);
    process.exit(1);
  }

  // Create the output directory if it doesn't exist
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
    process.stdout.write(`Created output directory: ${outDir}\n`);
  }

  // Load menu items mapping first
  const menuItemsList: { title: string; url: string }[] = [];

  if (menuConfig === 'auto' || !menuConfig) {
    const indexExists = fs.existsSync(path.join(srcDir, 'index.md'));
    const readmeExists = fs.existsSync(path.join(srcDir, 'README.md'));
    
    if (indexExists) {
      menuItemsList.push({ title: 'Home', url: 'index.html' });
    } else if (readmeExists) {
      menuItemsList.push({ title: 'README', url: 'README.html' });
    }

    const otherFiles = mdFiles.filter(f => f !== 'index.md' && f !== 'README.md');
    for (const file of otherFiles) {
      const fullPath = path.join(srcDir, file);
      const baseName = path.basename(file, '.md');
      const info = getMarkdownInfo(fullPath, baseName);
      menuItemsList.push({ title: info.title, url: `${baseName}.html` });
    }
  } else if (menuConfig !== 'none') {
    try {
      const jsonPath = path.resolve(menuConfig);
      if (fs.existsSync(jsonPath)) {
        const content = fs.readFileSync(jsonPath, 'utf-8');
        const customMenu = JSON.parse(content);
        if (Array.isArray(customMenu)) {
          for (const item of customMenu) {
            menuItemsList.push({ title: item.title, url: item.url });
          }
        }
      }
    } catch (err: any) {
      process.stdout.write(`Warning: Failed to load menu config json: ${err.message}. Falling back to 'auto'.\n`);
      menuConfig = 'auto';
    }
  } else {
    // none - just add index.html/README.html if exist
    const indexExists = fs.existsSync(path.join(srcDir, 'index.md'));
    const readmeExists = fs.existsSync(path.join(srcDir, 'README.md'));
    if (indexExists) {
      menuItemsList.push({ title: 'Home', url: 'index.html' });
    } else if (readmeExists) {
      menuItemsList.push({ title: 'README', url: 'README.html' });
    }
  }

  // Resolve Home Link URL
  const indexExists = fs.existsSync(path.join(srcDir, 'index.md'));
  const homeLinkUrl = indexExists ? 'index.html' : 'README.html';

  // Pre-process and render Markdown content to compile the Search Index
  const searchIndex: { title: string; url: string; content: string }[] = [];
  const processedFiles: {
    fileName: string;
    baseName: string;
    title: string;
    bodyHTML: string;
    tocHTML: string;
  }[] = [];

  for (const file of mdFiles) {
    const fullPath = path.join(srcDir, file);
    const baseName = path.basename(file, '.md');
    const info = getMarkdownInfo(fullPath, baseName);
    
    let rawContent = '';
    try {
      rawContent = fs.readFileSync(fullPath, 'utf-8');
    } catch {
      continue;
    }

    // Strip metadata sections if generated by wiki (e.g. --- \n name: index \n ---)
    let markdownToParse = rawContent;
    if (rawContent.startsWith('---')) {
      const endMeta = rawContent.indexOf('---', 3);
      if (endMeta !== -1) {
        markdownToParse = rawContent.slice(endMeta + 3).trim();
      }
    }

    // Parse Markdown to HTML
    const renderedBody = parseMarkdown(markdownToParse);
    
    // Auto-generate TOC
    const { tocHTML, bodyHTML } = generateTOC(renderedBody);

    // Prepare search index content — strip markdown syntax for clean text
    const textOnly = markdownToParse
      .replace(/```[\s\S]*?```/g, '') // remove code blocks
      .replace(/<[^>]*>/g, '') // remove HTML tags
      .replace(/\[\[([^\]]+?)\]\]/g, (_, t) => t.includes('|') ? t.split('|')[1].trim() : t.trim()) // wikilinks → text
      .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1') // [text](url) → text
      .replace(/!\[[^\]]*\]\([^)]+\)/g, '') // images
      .replace(/^#{1,6}\s+/gm, '') // heading markers
      .replace(/\*\*(.*?)\*\*/g, '$1') // bold
      .replace(/\*(.*?)\*/g, '$1') // italic
      .replace(/`([^`]+)`/g, '$1') // inline code
      .replace(/^[-*+]\s+/gm, '') // list markers
      .replace(/^\d+\.\s+/gm, '') // ordered list markers
      .replace(/^>\s?/gm, '') // blockquotes
      .replace(/\|/g, ' ') // table pipes
      .replace(/---+/g, ' ') // horizontal rules
      .replace(/\r?\n/g, ' ') // normalize whitespace
      .replace(/\s+/g, ' ')
      .trim();

    const outputHtmlFileName = baseName === 'index' ? 'index.html' : `${baseName}.html`;
    searchIndex.push({
      title: info.title,
      url: outputHtmlFileName,
      content: textOnly
    });

    processedFiles.push({
      fileName: file,
      baseName,
      title: info.title,
      bodyHTML,
      tocHTML
    });
  }

  // Write the search index file (CORS-safe global variable)
  const searchIndexJsContent = `const WIKI_SEARCH_INDEX = ${JSON.stringify(searchIndex, null, 2)};`;
  fs.writeFileSync(path.join(outDir, 'search-index.js'), searchIndexJsContent, 'utf-8');

  // Process and write HTML files
  for (let idx = 0; idx < processedFiles.length; idx++) {
    const file = processedFiles[idx];
    const outputHtmlFileName = file.baseName === 'index' ? 'index.html' : `${file.baseName}.html`;
    const outputFile = path.join(outDir, outputHtmlFileName);

    // Sidebar navigation rendering with active page highlight
    const sidebarHTML = buildNavigationMenu(srcDir, menuConfig, file.baseName, menuItemsList);

    // Previous & Next navigation buttons
    let prevButton = '';
    let nextButton = '';
    
    // Find index of current file in the menuItemsList
    const menuIdx = menuItemsList.findIndex(item => item.url === outputHtmlFileName);
    if (menuIdx !== -1) {
      if (menuIdx > 0) {
        const prevItem = menuItemsList[menuIdx - 1];
        prevButton = `
          <a href="${prevItem.url}" class="pagination-link prev">
            <span class="pagination-label">Previous</span>
            <span class="pagination-title">${escapeHtml(prevItem.title)}</span>
          </a>
        `;
      }
      if (menuIdx < menuItemsList.length - 1) {
        const nextItem = menuItemsList[menuIdx + 1];
        nextButton = `
          <a href="${nextItem.url}" class="pagination-link next">
            <span class="pagination-label">Next</span>
            <span class="pagination-title">${escapeHtml(nextItem.title)}</span>
          </a>
        `;
      }
    }

    const paginationHTML = `
      <div class="pagination">
        ${prevButton}
        ${nextButton}
      </div>
    `;

    // Inject variable values into the main template — escape HTML in user-provided values
    const safeTitle = escapeHtml(title);
    const safeFileTitle = escapeHtml(file.title);
    const safeColor = primaryColor.replace(/[^#0-9a-fA-F]/g, '');
    const finalHTML = HTML_TEMPLATE
      .replace(/\$title\$/g, `${safeTitle} - ${safeFileTitle}`)
      .replace(/PRIMARYCOLOR/g, safeColor)
      .replace(/\$ProjectTitle\$/g, safeTitle)
      .replace(/HOME_LINK_URL/g, homeLinkUrl)
      .replace(/NAVIGATION/g, sidebarHTML)
      .replace(/TOC/g, file.tocHTML)
      .replace(/BODY/g, file.bodyHTML)
      .replace(/PAGINATION/g, paginationHTML);

    fs.writeFileSync(outputFile, finalHTML, 'utf-8');
  }

  process.stdout.write(`[SUCCESS] Documentation generated successfully!\n`);
  process.stdout.write(`[SUCCESS] HTML files are in ${outDir} (${processedFiles.length} pages generated)\n`);

  if (openBrowser) {
    let indexPath = path.join(outDir, 'index.html');
    if (!fs.existsSync(indexPath)) {
      indexPath = path.join(outDir, 'README.html');
    }

    if (fs.existsSync(indexPath)) {
      process.stdout.write(`Opening ${indexPath} in your default browser...\n`);
      const startCmd = process.platform === 'darwin' ? 'open' : process.platform === 'win32' ? 'start' : 'xdg-open';
      execFile(startCmd, [indexPath], (err) => {
        if (err) {
          process.stdout.write(`Warning: Could not open browser automatically. Please open the file manually: ${indexPath}\n`);
        }
      });
    }
  }
}
